#############################################################################
# Makefile for building: bin/qfetion
# Generated by qmake (2.01a) (Qt 4.7.3) on: Thu Jun 2 11:59:31 2011
# Project:  qfetion.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qfetion.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -Wno-deprecated -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Iinclude -Itmp/moc -Iinclude/ui
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtXml -L/usr/lib64 -L/usr/lib64/qt4 -lQtGui -L/usr/X11R6/lib -lQtNetwork -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = tmp/obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/console.cpp \
		src/control.cpp \
		src/logintossiportal.cpp \
		src/siptalk.cpp \
		src/sipword.cpp \
		src/chatwindow.cpp \
		src/contact.cpp \
		src/contactlistitem.cpp \
		src/sysconfig.cpp \
		src/userinfo.cpp \
		src/test.cpp \
		src/utilities.cpp \
		src/aboutdialog.cpp \
		src/proxysetting.cpp tmp/moc/moc_mainwindow.cpp \
		tmp/moc/moc_console.cpp \
		tmp/moc/moc_control.cpp \
		tmp/moc/moc_logintossiportal.cpp \
		tmp/moc/moc_siptalk.cpp \
		tmp/moc/moc_sipword.cpp \
		tmp/moc/moc_chatwindow.cpp \
		tmp/moc/moc_contact.cpp \
		tmp/moc/moc_contactlistitem.cpp \
		tmp/moc/moc_sysconfig.cpp \
		tmp/moc/moc_userinfo.cpp \
		tmp/moc/moc_test.cpp \
		tmp/moc/moc_aboutdialog.cpp \
		tmp/moc/moc_proxysetting.cpp \
		tmp/rcc/qrc_images.cpp
OBJECTS       = tmp/obj/main.o \
		tmp/obj/mainwindow.o \
		tmp/obj/console.o \
		tmp/obj/control.o \
		tmp/obj/logintossiportal.o \
		tmp/obj/siptalk.o \
		tmp/obj/sipword.o \
		tmp/obj/chatwindow.o \
		tmp/obj/contact.o \
		tmp/obj/contactlistitem.o \
		tmp/obj/sysconfig.o \
		tmp/obj/userinfo.o \
		tmp/obj/test.o \
		tmp/obj/utilities.o \
		tmp/obj/aboutdialog.o \
		tmp/obj/proxysetting.o \
		tmp/obj/moc_mainwindow.o \
		tmp/obj/moc_console.o \
		tmp/obj/moc_control.o \
		tmp/obj/moc_logintossiportal.o \
		tmp/obj/moc_siptalk.o \
		tmp/obj/moc_sipword.o \
		tmp/obj/moc_chatwindow.o \
		tmp/obj/moc_contact.o \
		tmp/obj/moc_contactlistitem.o \
		tmp/obj/moc_sysconfig.o \
		tmp/obj/moc_userinfo.o \
		tmp/obj/moc_test.o \
		tmp/obj/moc_aboutdialog.o \
		tmp/obj/moc_proxysetting.o \
		tmp/obj/qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		src/src.pri \
		include/include.pri \
		form/form.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		qfetion.pro
QMAKE_TARGET  = qfetion
DESTDIR       = bin/
TARGET        = bin/qfetion

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): include/ui/ui_mainwindow.h include/ui/ui_console.h include/ui/ui_chatwindow.h include/ui/ui_contactlistitem.h include/ui/ui_test.h include/ui/ui_aboutdialog.h include/ui/ui_proxysetting.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qfetion.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		src/src.pri \
		include/include.pri \
		form/form.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -o Makefile qfetion.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
src/src.pri:
include/include.pri:
form/form.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qfetion.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp/obj/qfetion1.0.0 || $(MKDIR) tmp/obj/qfetion1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp/obj/qfetion1.0.0/ && $(COPY_FILE) --parents include/mainwindow.h include/console.h include/control.h include/logintossiportal.h include/siptalk.h include/sipword.h include/chatwindow.h include/contact.h include/contactlistitem.h include/sysconfig.h include/userinfo.h include/test.h include/utilities.h include/aboutdialog.h include/global.h include/proxysetting.h tmp/obj/qfetion1.0.0/ && $(COPY_FILE) --parents images/images.qrc tmp/obj/qfetion1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/console.cpp src/control.cpp src/logintossiportal.cpp src/siptalk.cpp src/sipword.cpp src/chatwindow.cpp src/contact.cpp src/contactlistitem.cpp src/sysconfig.cpp src/userinfo.cpp src/test.cpp src/utilities.cpp src/aboutdialog.cpp src/proxysetting.cpp tmp/obj/qfetion1.0.0/ && $(COPY_FILE) --parents form/mainwindow.ui form/console.ui form/chatwindow.ui form/contactlistitem.ui form/test.ui form/aboutdialog.ui form/proxysetting.ui tmp/obj/qfetion1.0.0/ && $(COPY_FILE) --parents translations/qfetion_zh_CN.ts tmp/obj/qfetion1.0.0/ && (cd `dirname tmp/obj/qfetion1.0.0` && $(TAR) qfetion1.0.0.tar qfetion1.0.0 && $(COMPRESS) qfetion1.0.0.tar) && $(MOVE) `dirname tmp/obj/qfetion1.0.0`/qfetion1.0.0.tar.gz . && $(DEL_FILE) -r tmp/obj/qfetion1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: tmp/moc/moc_mainwindow.cpp tmp/moc/moc_console.cpp tmp/moc/moc_control.cpp tmp/moc/moc_logintossiportal.cpp tmp/moc/moc_siptalk.cpp tmp/moc/moc_sipword.cpp tmp/moc/moc_chatwindow.cpp tmp/moc/moc_contact.cpp tmp/moc/moc_contactlistitem.cpp tmp/moc/moc_sysconfig.cpp tmp/moc/moc_userinfo.cpp tmp/moc/moc_test.cpp tmp/moc/moc_aboutdialog.cpp tmp/moc/moc_proxysetting.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp/moc/moc_mainwindow.cpp tmp/moc/moc_console.cpp tmp/moc/moc_control.cpp tmp/moc/moc_logintossiportal.cpp tmp/moc/moc_siptalk.cpp tmp/moc/moc_sipword.cpp tmp/moc/moc_chatwindow.cpp tmp/moc/moc_contact.cpp tmp/moc/moc_contactlistitem.cpp tmp/moc/moc_sysconfig.cpp tmp/moc/moc_userinfo.cpp tmp/moc/moc_test.cpp tmp/moc/moc_aboutdialog.cpp tmp/moc/moc_proxysetting.cpp
tmp/moc/moc_mainwindow.cpp: include/control.h \
		include/siptalk.h \
		include/userinfo.h \
		include/sipword.h \
		include/ui/ui_mainwindow.h \
		include/mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/mainwindow.h -o tmp/moc/moc_mainwindow.cpp

tmp/moc/moc_console.cpp: include/ui/ui_console.h \
		include/console.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/console.h -o tmp/moc/moc_console.cpp

tmp/moc/moc_control.cpp: include/siptalk.h \
		include/userinfo.h \
		include/sipword.h \
		include/control.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/control.h -o tmp/moc/moc_control.cpp

tmp/moc/moc_logintossiportal.cpp: include/logintossiportal.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/logintossiportal.h -o tmp/moc/moc_logintossiportal.cpp

tmp/moc/moc_siptalk.cpp: include/userinfo.h \
		include/siptalk.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/siptalk.h -o tmp/moc/moc_siptalk.cpp

tmp/moc/moc_sipword.cpp: include/sipword.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/sipword.h -o tmp/moc/moc_sipword.cpp

tmp/moc/moc_chatwindow.cpp: include/ui/ui_chatwindow.h \
		include/control.h \
		include/siptalk.h \
		include/userinfo.h \
		include/sipword.h \
		include/chatwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/chatwindow.h -o tmp/moc/moc_chatwindow.cpp

tmp/moc/moc_contact.cpp: include/message.h \
		include/control.h \
		include/siptalk.h \
		include/userinfo.h \
		include/sipword.h \
		include/contact.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/contact.h -o tmp/moc/moc_contact.cpp

tmp/moc/moc_contactlistitem.cpp: include/ui/ui_contactlistitem.h \
		include/contactlistitem.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/contactlistitem.h -o tmp/moc/moc_contactlistitem.cpp

tmp/moc/moc_sysconfig.cpp: include/sysconfig.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/sysconfig.h -o tmp/moc/moc_sysconfig.cpp

tmp/moc/moc_userinfo.cpp: include/userinfo.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/userinfo.h -o tmp/moc/moc_userinfo.cpp

tmp/moc/moc_test.cpp: include/test.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/test.h -o tmp/moc/moc_test.cpp

tmp/moc/moc_aboutdialog.cpp: include/ui/ui_aboutdialog.h \
		include/aboutdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/aboutdialog.h -o tmp/moc/moc_aboutdialog.cpp

tmp/moc/moc_proxysetting.cpp: include/proxysetting.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/proxysetting.h -o tmp/moc/moc_proxysetting.cpp

compiler_rcc_make_all: tmp/rcc/qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) tmp/rcc/qrc_images.cpp
tmp/rcc/qrc_images.cpp: images/images.qrc \
		images/people.png \
		images/space.png \
		images/phone_chat.png \
		images/client_dis.png \
		images/love.png \
		images/sms_dis.png \
		images/client_chat.png \
		images/sun.gif \
		images/client_ena.png \
		images/sms_ena.png \
		images/pet_dis.png \
		images/pet_ena.png \
		images/friend.png
	/usr/bin/rcc -name images images/images.qrc -o tmp/rcc/qrc_images.cpp

compiler_image_collection_make_all: form/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) form/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: include/ui/ui_mainwindow.h include/ui/ui_console.h include/ui/ui_chatwindow.h include/ui/ui_contactlistitem.h include/ui/ui_test.h include/ui/ui_aboutdialog.h include/ui/ui_proxysetting.h
compiler_uic_clean:
	-$(DEL_FILE) include/ui/ui_mainwindow.h include/ui/ui_console.h include/ui/ui_chatwindow.h include/ui/ui_contactlistitem.h include/ui/ui_test.h include/ui/ui_aboutdialog.h include/ui/ui_proxysetting.h
include/ui/ui_mainwindow.h: form/mainwindow.ui
	/usr/bin/uic form/mainwindow.ui -o include/ui/ui_mainwindow.h

include/ui/ui_console.h: form/console.ui
	/usr/bin/uic form/console.ui -o include/ui/ui_console.h

include/ui/ui_chatwindow.h: form/chatwindow.ui
	/usr/bin/uic form/chatwindow.ui -o include/ui/ui_chatwindow.h

include/ui/ui_contactlistitem.h: form/contactlistitem.ui
	/usr/bin/uic form/contactlistitem.ui -o include/ui/ui_contactlistitem.h

include/ui/ui_test.h: form/test.ui
	/usr/bin/uic form/test.ui -o include/ui/ui_test.h

include/ui/ui_aboutdialog.h: form/aboutdialog.ui
	/usr/bin/uic form/aboutdialog.ui -o include/ui/ui_aboutdialog.h

include/ui/ui_proxysetting.h: form/proxysetting.ui
	/usr/bin/uic form/proxysetting.ui -o include/ui/ui_proxysetting.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

tmp/obj/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/main.o src/main.cpp

tmp/obj/mainwindow.o: src/mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/mainwindow.o src/mainwindow.cpp

tmp/obj/console.o: src/console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/console.o src/console.cpp

tmp/obj/control.o: src/control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/control.o src/control.cpp

tmp/obj/logintossiportal.o: src/logintossiportal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/logintossiportal.o src/logintossiportal.cpp

tmp/obj/siptalk.o: src/siptalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/siptalk.o src/siptalk.cpp

tmp/obj/sipword.o: src/sipword.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/sipword.o src/sipword.cpp

tmp/obj/chatwindow.o: src/chatwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/chatwindow.o src/chatwindow.cpp

tmp/obj/contact.o: src/contact.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/contact.o src/contact.cpp

tmp/obj/contactlistitem.o: src/contactlistitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/contactlistitem.o src/contactlistitem.cpp

tmp/obj/sysconfig.o: src/sysconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/sysconfig.o src/sysconfig.cpp

tmp/obj/userinfo.o: src/userinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/userinfo.o src/userinfo.cpp

tmp/obj/test.o: src/test.cpp include/ui/ui_test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/test.o src/test.cpp

tmp/obj/utilities.o: src/utilities.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/utilities.o src/utilities.cpp

tmp/obj/aboutdialog.o: src/aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/aboutdialog.o src/aboutdialog.cpp

tmp/obj/proxysetting.o: src/proxysetting.cpp include/ui/ui_proxysetting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/proxysetting.o src/proxysetting.cpp

tmp/obj/moc_mainwindow.o: tmp/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_mainwindow.o tmp/moc/moc_mainwindow.cpp

tmp/obj/moc_console.o: tmp/moc/moc_console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_console.o tmp/moc/moc_console.cpp

tmp/obj/moc_control.o: tmp/moc/moc_control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_control.o tmp/moc/moc_control.cpp

tmp/obj/moc_logintossiportal.o: tmp/moc/moc_logintossiportal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_logintossiportal.o tmp/moc/moc_logintossiportal.cpp

tmp/obj/moc_siptalk.o: tmp/moc/moc_siptalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_siptalk.o tmp/moc/moc_siptalk.cpp

tmp/obj/moc_sipword.o: tmp/moc/moc_sipword.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_sipword.o tmp/moc/moc_sipword.cpp

tmp/obj/moc_chatwindow.o: tmp/moc/moc_chatwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_chatwindow.o tmp/moc/moc_chatwindow.cpp

tmp/obj/moc_contact.o: tmp/moc/moc_contact.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_contact.o tmp/moc/moc_contact.cpp

tmp/obj/moc_contactlistitem.o: tmp/moc/moc_contactlistitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_contactlistitem.o tmp/moc/moc_contactlistitem.cpp

tmp/obj/moc_sysconfig.o: tmp/moc/moc_sysconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_sysconfig.o tmp/moc/moc_sysconfig.cpp

tmp/obj/moc_userinfo.o: tmp/moc/moc_userinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_userinfo.o tmp/moc/moc_userinfo.cpp

tmp/obj/moc_test.o: tmp/moc/moc_test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_test.o tmp/moc/moc_test.cpp

tmp/obj/moc_aboutdialog.o: tmp/moc/moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_aboutdialog.o tmp/moc/moc_aboutdialog.cpp

tmp/obj/moc_proxysetting.o: tmp/moc/moc_proxysetting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/moc_proxysetting.o tmp/moc/moc_proxysetting.cpp

tmp/obj/qrc_images.o: tmp/rcc/qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/obj/qrc_images.o tmp/rcc/qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

